name: CI

on:
  push:
    branches:
      - github-actions-sonarcloud

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        eclipse: [4.11]
    name: 'Eclipse ${{ matrix.eclipse }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          # SonarCloud requires Java 11 for new projects
          java-version: 11
      - run: |
          sudo apt-get update
          sudo apt-get install metacity
          export DISPLAY=:99.0
          Xvfb :99 &
          sleep 5
          metacity --sm-disable --replace 2> metacity.err &
          mvn -V -B -e verify -P e${{ matrix.eclipse }} -DskipUITests=false sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=godin-github -Dsonar.projectKey=godin:eclemma
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: cat org.eclipse.eclemma.ui.test/target/work/data/.metadata/.log
        if: ${{ failure() }}
