name: CI

on:
  push:
    branches:
      - godin/github-actions_windows

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        eclipse: [3.8, 4.6, 4.7, 4.8, 4.9, '4.10', 4.11, 4.12, 4.13]
        os: [ubuntu-18.04, windows-latest]
    name: 'Eclipse ${{ matrix.eclipse }} / ${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - if: matrix.os == 'windows-latest'
        run: |
          mvn -V -B -e verify -P e${{ matrix.eclipse }} -DskipUITests=false
      - if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt-get update
          sudo apt-get install metacity
          export DISPLAY=:99.0
          Xvfb :99 &
          sleep 5
          metacity --sm-disable --replace 2> metacity.err &
          mvn -V -B -e verify -P e${{ matrix.eclipse }} -DskipUITests=false
