name: SimRel

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - godin/simrel_2020-12

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        eclipse: [4.18]
    name: 'Eclipse ${{ matrix.eclipse }}'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: godin/simrel_2020-12
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: |
          sudo apt-get update
          sudo apt-get install metacity
          export DISPLAY=:99.0
          Xvfb :99 &
          sleep 5
          metacity --sm-disable --replace 2> metacity.err &
          mvn -V -B -e verify -P e${{ matrix.eclipse }} -DskipUITests=false
